### PR TITLE
Final fixes

### LINKED ISSUE #15: Deployed application on Heroku
Deployed at : https://calm-island-40203.herokuapp.com/notes
Can be logged in using:
Username : oliver@example.com
Password : welcome

@yedhink Please review.

### PR DESCRIPTION
**Pull request by aagneyanNamboodiri**
Fixes #15 
List of changes done:
- [X] Fixed note validation schema
- [X] Removed linting comments
- [X] Modified `Cancel` button in new contact UI
- [X] Added contact deletion UI

### CODE REVIEW

**Comment by yedhink** [comment]
@aagneyanNamboodiri Go through https://handbook.neetokb.com/articles/git-and-github-essentials once again and see if you need make any more changes in this PR. Once you verify, lemme know.

**Comment by aagneyanNamboodiri** [comment]
@yedhink I have gone through the article, and have made changes to this PR.

File: app/javascript/src/components/Dashboard/Contacts/DeleteAlert.jsx [hunk 1]
```diff
@@ -0,0 +1,27 @@
+import React from "react";
+
+import { Alert, Toastr } from "neetoui";
+
+const DeleteAlert = ({ onClose, setShowDeleteAlert }) => {
+  const deleteNotePrompt = "Delete this Contact?";
+  const deleteNoteMessage =
+    "Are you sure you want to continue? This cannot be undone.";
+  const toasterSuccess = "Contact deleted successfully";
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Contacts/DeleteAlert.jsx:9]: These variables are pretty unnecessary at this moment within this component. Even if these variables were not present the idea would have been conveyed in this component because these are straightforward messages. The component is very small and these variables don't have reusability.

But I would like to know your reasoning for adding these variables. Maybe you had seen a use case for them which I am not able to see, yet.

File: app/javascript/src/components/Dashboard/Notes/constants.js [hunk 2]
```diff
@@ -50,13 +47,31 @@ export const USER_IMG_URL =
...
+    .required("Please select a contact"),
+  tags: yup
+    .array()
+    .of(
+      yup.object().shape({
+        label: yup.string().oneOf(TAG_OPTIONS.map(tag => tag.label)),
+        value: yup.string().oneOf(TAG_OPTIONS.map(tag => tag.value)),
+      })
+    )
+    .min(1, "Every note should have atleast 1 tag")
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/constants.js:73]: This validation message is too long and verbose. Keep it compact.

**Review by yedhink — COMMENTED** [review]
@aagneyanNamboodiri

**Comment by yedhink** [comment]
@aagneyanNamboodiri The validation messages should have some consistency in the way they are being pointed out to the end user.

Can you comment on what you feel about the consistency in the sentence construction of the following messages? Do you see a scope for improvement?
image

File: app/javascript/src/components/Dashboard/Contacts/DeleteAlert.jsx (hunk 1 above)
Comment (aagneyanNamboodiri) [reply app/javascript/src/components/Dashboard/Contacts/DeleteAlert.jsx:9]: I added the messages as variables as I felt it was better to just use the variable in-place of the actual string.
But as you had mentioned, the strings don't have re-usability, and the scope of usage for the component is just for the contact namespace, I think it is better to just use them as direct string messages than adding them as a variable.

File: app/javascript/src/components/Dashboard/Notes/constants.js (hunk 2 above)
Comment (aagneyanNamboodiri) [reply app/javascript/src/components/Dashboard/Notes/constants.js:73]: > @aagneyanNamboodiri The validation messages should have some consistency in the way they are being pointed out to the end user.
> 
> Can you comment on what you feel about the consistency in the sentence construction of the following messages? Do you see a scope for improvement? image

The error messages do seem inconsistent. 
I think just saying "Please select a tag" will be sufficient here. Also, it is similar to the previous for select's validation message which makes it easier for the user to understand.
